version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - run:
          name: Dhall
          command: stack install dhall
      - run:
          name: Compile
          command: make compile
